# Generated by Django 3.1.4 on 2023-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
